#!build/venv/bin/python

"""Usage: bluejay [-u] VAULT_PATH [-r REPO_PATH]

    -h --help          Show this message.
    -r REPO_PATH       Path to the git repo. [default: /tmp/bluejay/vlt].
    -u --unlock        Unlock the vault into the repo directory.
    VAULT_PATH         Path to the vault directory (optionally vault revision file if unlocking).
"""

import os
import sys
import logging
from docopt import docopt

from lib.vault import VaultLocker, VaultUnlocker

logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S', level=logging.DEBUG)

if __name__ == "__main__":
    args = docopt(__doc__)
    vault_path = os.path.abspath(args["VAULT_PATH"])
    repo_path = os.path.abspath(args["-r"])

    logging.debug(f"VAULT_PATH: {vault_path}")
    logging.debug(f"REPO_PATH: {repo_path}")

    if args["--unlock"]:
        with VaultUnlocker(vault_path, repo_path) as runner:
            if not runner.execute():
                print("Failed to unlock the input vault.")
            else:
                print("Successfully unlocked the input vault.")
    else:
        with VaultLocker(vault_path, repo_path) as runner:
            if not runner.execute():
                print("Failed to lock the input repository.")
            else:
                print("Successfully locked the input repository.")
